name: Publicar Pagina a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura Node.js  
        uses: actions/setup-node@v3
        with:
            node-version: '18'

      - name: Instala Surge       
        run: npm install --global surge

      - name: Publicar pagina
run: surge --project ./ --domain pavel.surge.sh --token 4dbd209c805208891ed3c922fbdb92e0
